<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Fishbone.Hosting.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fishbone.Core\Fishbone.Core.csproj" />
    <ProjectReference Include="..\Fishbone.Engine\Fishbone.Engine.csproj" />
  </ItemGroup>

</Project>